#!/bin/bash --noprofile

# For more detailed documentation, see zrep.txt or zrep.overview.txt
# note to self: always make this 3 fields
ZREP_VERSION=2.1.0

################################################

#### File: zrep_top

######## start of included files from zrep_top here
AWKinclude zrep_vars
AWKinclude zrep_status
AWKinclude zrep_snap
AWKinclude zrep_sync
AWKinclude zrep_failover

######## File: zrep_top continues here

usage(){
	echo zrep v${ZREP_VERSION}: a program to replicate a zfs filesystem to another
	echo in an ongoing basis.
	echo 
	echo "  Philip Brown, 2012-2023"
	echo 
	echo Usage summary:
	echo 'zrep (init|-i) [-f] [-v] ZFS/fs remotehost remoteZFSpool/fs'
	echo 'zrep (sync|-S) [-f] [-v] [-q seconds] ZFS/fs'
	echo 'zrep (sync|-S) [-f] [-v] [-q seconds] all'
	echo 'zrep (sync|-S) [-f] [-v] ZFS/fs snapshot  -- temporary retroactive sync'
	echo 'zrep refresh [-f] [-v] ZFS/fs             -- pull partner of sync'
	echo 'zrep failover [-L] ZFS/fs [remotehost]'
	echo 'zrep takeover [-L] ZFS/fs [remotehost]'
	echo 
	echo "Status and side operations"
	echo 'zrep (status|-s) [-v] [(-a|ZFS/fs)]'
	echo 'zrep (status|-s) -m [ZFS/fs]'
	echo 'zrep (list|-l) [-Lv]  [fs/names]'
	echo 'zrep (list|-l) -s     [fs/names]  -- list all relevant zrep snapshots'
	echo 'zrep getlastsent ZFS/fs    -- prints out snapshot of last successful sync sent'
	echo 'zrep (expire|-e) [-L] (ZFS/fs ...)|(all)|()'
	echo 'zrep uptodate ZFS/fs    -- returns 0 if no writes since last sync.'
	echo 'zrep version'
	echo 'zrep clear [-f] ZFS/fs  -- REMOVE ZREP CONFIG AND SNAPS FROM FILESYSTEM'
	echo 'zrep (changeconfig|-C) [-f] ZFS/fs remotehost remoteZFSpool/fs'
	echo 'zrep (changeconfig|-C) [-f] [-d] ZFS/fs srchost srcZFSpool/fs'
	echo ''
	echo '   sync -q option says to Quietly ignore locked filesystems'
	echo '    that have synced more recently than the given amount of seconds'
	echo ''
	echo 'Paired commands for high-transaction systems:'
	echo '   zrep snaponly (ZFS/fs ... |all)'
	echo '   zrep synconly (ZFS/fs ...|all)'
	echo 'The above two commands split the simple sync subcommand, into two'
	echo 'separate steps, so that a database, etc. may resume while the sync'
	echo 'completes in the background'
	echo ''
	echo 'zrep defaults to using ssh. However, if remotehost is set to localhost,'
	echo 'zrep will use a simple pipe instead.'
	echo ''
	echo ' More detailed examples can be found at:'
	echo http://www.bolthole.com/solaris/zrep/zrep.documentation.html
	echo ''
	echo 'See the above documentation for details on using the -t flag to use zrep tags'
}

GLOBALFLAGS=""
#
# Special global flags that must always be processed FIRST, before normal command args.
# But maybe I should transition global flags to --longarg format
#
while [[ "$1" == -[tDR] ]] ; do
	case "$1" in
	    -D)
		DEBUG=1
		GLOBALFLAGS=-D
		shift
		;;
	    -R)
		# If you want to recursively create/send snapshots
		ZREP_R=-R
		GLOBALFLAGS+=" -R"
		shift
		;;
	    -t)  # or use --tag
		if [ "$2" == "" ] ; then
		usage
		fi
		#deliberately dont quote this to avoid stupidity or malice by user
		ZREPTAG=$2
		shift
		shift
		GLOBALFLAGS+=" -t $ZREPTAG"
		;;
	esac
done

# Backward compatibility hack
if [[ "ZREP_R" != "" ]] && [[ "$GLOBALFLAGS" != *"-R"* ]] ; then
	GLOBALFLAGS+=" -R"
fi

## Arg. Maybe I should standardize on longopts.
## Useful here, but I hate the extra typing
## This section, is for longopt parsing. zrep currently uses these
## ONLY for global options.
## These will get passed to any remote invocation of zrep.
## (This is neccessary because "ssh remotehost zrep" does not
## pass through environment vars
## Therre are probably a few historical options that should be 
## migrated to use this now
while [[ "$1" == "--" ]] ; do
	case "$1" in
		--allincrementals)
			GLOBALFLAGS+="$1"
			ZREP_INC_FLAG="-I"
			shift
		;;
		--notallincrementals)
			GLOBALFLAGS+="$1"
			ZREP_INC_FLAG="-i"
			shift
		;;
		--debug)
			GLOBALFLAGS+="$1"
			DEBUG=1
			shift
		;;
		--tag)
			GLOBALFLAGS+="$1 $2"
			ZREPTAG=$2
			shift
			shift
		;;
		*)
			echo error: unrecognized flag $1
		;;
	esac
done



# Special polymorphic handling that must be done HERE specifically
if [[ "$ZREPTAG" != "zrep" ]] ; then
	# If custom zrep tag, then probably multiple layers of snapshots.
	# In this case, DO NOT send all intermediate snapshots for replication
	ZREP_INC_FLAG=${ZREP_INC_FLAG:-"-i"}

	if [ "$ZREPTAG" != "" ] ; then
	    ZREP_PATH="$ZREP_PATH -t $ZREPTAG"
	fi
fi
# ensure it is set to SOMETHING by default. Default is to send all
ZREP_INC_FLAG=${ZREP_INC_FLAG:-"-I"}



# yes, a by-hand variant of getopt
# This is only because I prefer "longoption" to "--longoption"
# Although most of these are actually subcommands, not "options"

case "$1" in
	"")
		usage
		;;
	changeconfig|-C)
		shift
		zrep_changeconfig "$@"
		;;
	clear)
		shift
		# only actually allows ONE fs
		if [[ "$1" == "-f" ]] ; then
			shift
			ZREP_FORCE=-f
		fi
		zrep_clear "$@"
		;;
	expire|-e)
		shift
		zrep_expire "$@"
		;;
	init|-i)
		shift
		while  [ "$1" != "" ] ; do
			case $1 in
				"-f")
				shift
				ZREP_FORCE=-f
				;;
				"-v")
				shift
				ZREP_VERBOSE=yes
				;;
				*)
				break
				;;
			esac
		done
		zrep_init "$@"
		;;
	sentsync)
		shift
		# Note that this will NOT accept multiple snaps, for safety
		zrep_sentsync "$@" 
		;;
	snaponly)
		shift
		zrep_snaponly "$@"
		;;
	sync|-S)  #remember, this is inverse of refresh
		shift
		while  [ "$1" != "" ] ; do
			case $1 in
				"-f")
				shift
				ZREP_FORCE=-f
				;;
				"-v")
				shift
				ZREP_VERBOSE=yes
				;;
				"-r")
				shift
				ZREP_RESUME=yes
				;;
				*)
				break
				;;
			esac
		done
		zrep_sync "$@"
		;;
	synconly)
		shift
		zrep_synconly "$@"
		;;
	refresh)	# yes keep this in this order
		shift
		while  [ "$1" != "" ] ; do
			case $1 in
				"-f")
				shift
				ZREP_FORCE=-f
				;;
				"-v")
				shift
				ZREP_VERBOSE=yes
				;;
				"-r")
				shift
				ZREP_RESUME=yes
				;;
				*)
				break
				;;
			esac
		done
		zrep_refresh "$@"
		;;
	status|-s)
		shift
		zrep_status "$@"
		;;
	list|-l)
		shift
		zrep_list "$@"
		;;
	lastsent|getlastsent)
		# lastsent is a backward compability hook.
		shift
		zrep_getlastsent "$@"
		;;
	failover)
		shift
		if [[ "$1" == "-f" ]] ; then
			shift
			ZREP_FORCE=-f
		fi
		zrep_failover "$@"
		;;
	setlastsent)
		shift
		#zrep_setlastsent "$@"
		echo Nothing to see here. You might want sentsync. You might not.
		#  This kind of overlaps with "sentsync". Which may be poorly named
		#
		exit 1
		;;
	takeover)
		shift
		zrep_takeover "$@"
		;;
	uptodate)
		shift
		zrep_uptodate "$@"
		exit $?
		;;
	version)
		echo "zrep $ZREP_VERSION"
		echo "http://www.bolthole.com/solaris/zrep"
		echo "http://www.github.com/bolthole/zrep"
		exit
		;;
		
	_refreshpull)  # Secret option DO NOT PUT IN USAGE!!
		shift
		_refreshpull $@
		;;
	_refreshcomplete)  # Secret option DO NOT PUT IN USAGE!!
		shift
		_refreshcomplete $@
		;;
	*)
		echo "ERROR: unrecognized zrep subcommand $1"
		echo  "       Dont know what to do with: $0 $@"
		echo ""
		usage
		;;
esac


